using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.DevTools.V125.Page;
using OpenQA.Selenium.Support.UI;
using static System.Net.Mime.MediaTypeNames;

namespace HandlingFormInputs
{
    public class HandlingFormInputsTests
    {
        WebDriver driver;

        [SetUp]
        public void Setup()
        {
            driver = new ChromeDriver();
            driver.Navigate().GoToUrl("https://practice.bpbonline.com/");
        }

        [TearDown]

        public void TearDown() 
        {
            driver.Quit();
            driver.Dispose();
        }

        [Test]
        public void HandlingFormInputs()
        {
            //click on MyAccount Button
            driver.FindElements(By.XPath("//span[@class='ui-button-text']"))[2].Click();
            //click Continue Button
            driver.FindElement(By.LinkText("Continue")).Click();
            //click Radio Button "Male" with attribute 'm' in HTML
            driver.FindElement(By.XPath("//input[@type='radio'][@value='m']")).Click();
            //fill value in first name and last name fields
            driver.FindElement(By.XPath("//td[@class='fieldValue']//input[@name='firstname']")).SendKeys("Martin");
            driver.FindElement(By.XPath("//td[@class='fieldValue']//input[@name='lastname']")).SendKeys("Kirov");
            //Fill in date of birth
            driver.FindElement(By.Id("dob")).SendKeys("05/03/1987");
            //Generate RANDOM
            Random random = new Random();
            int randomNumber = random.Next(1000, 9999);
            string email = "martin" + randomNumber.ToString() + "@abv.bg";
            //Fill email field

            driver.FindElement(By.Name("email_address")).SendKeys(email);

            driver.FindElement(By.XPath("//input[@name='company']")).SendKeys("Mlad Merindjei"); 
            driver.FindElement(By.XPath("//input[@name='street_address']")).SendKeys("Ulica Todor Jivkov"); 
            driver.FindElement(By.XPath("//input[@name='suburb']")).SendKeys("Ulica Sofia");
            driver.FindElement(By.XPath("//input[@name='postcode']")).SendKeys("1000");
            driver.FindElement(By.XPath("//input[@name='city']")).SendKeys("Sofia");
            driver.FindElement(By.XPath("//input[@name='state']")).SendKeys("Sofia");
            driver.FindElement(By.XPath("//input[@name='suburb']")).SendKeys("Ulica Sofia");
            //dropdown menu usage - **(need nuget package SeleniumSupport)**
            new SelectElement(driver.FindElement(By.Name("country"))).SelectByText("Angola");
            //again normal fields
            driver.FindElement(By.XPath("//input[@type='text'][@name='telephone']")).SendKeys("123456789");
            driver.FindElement(By.XPath("//input[@type='checkbox'][@name='newsletter']")).Click();
            //password fill + password confirm
            driver.FindElement(By.XPath("//input[@name='password']")).SendKeys("123456789");
            driver.FindElement(By.XPath("//input[@name='confirmation']")).SendKeys("123456789");
            //find XPath of a child element that cannot be generated by usual means - (find ancestor then use sibling + number) NB***USE FINDELEMENTS***NB
            driver.FindElements(By.XPath("//span[@class='ui-button-icon-primary ui-icon ui-icon-person']//following-sibling::span"))[1].Click();
            //assert message for success
            Assert.AreEqual(driver.FindElement(By.XPath("//*[@id=\"bodyContent\"]/h1")).Text, "Your Account Has Been Created!");

            driver.FindElement(By.LinkText("Log Off")).Click();
            driver.FindElement(By.LinkText("Continue")).Click();
            Console.WriteLine("User Created Successfully!");
        }
    }
}